model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.finetune_ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "txt"
    image_size: 64
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: crossattn
    scale_factor: 0.18215

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      ckpt_path: "../../code/imagenet-autoencoder-main/assets/pretrained32x32x4.pt"
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        device: "cuda:0"

# ../../code/llm/LLaVA-13b/code/porn_defense1.csv
# ../../code/llm/LLaVA-13b/code/porn_defense2.csv
# ../../datasets/laion_2B_caption/image_text_data_28000.csv
# ../../code/llm/LLaVA-13b/code/llava_porn_finetune_I2T.csv
# ../../code/llm/LLaVA-13b/code/imagenet2ktrain.csv
# ../../datasets/laion_2B_caption/image_text_data_4000.csv
# ../../datasets/coco-image-caption/train5w.csv
data:
  target: src.utils.DataModuleFromConfig
  
  params:
    batch_size: 16
    num_workers: 0
    # num_val_workers: 0 # Avoid a weird val dataloader issue
    train_porn:
      target: ldm.data.simple.hf_dataset
      params:
        name: ../../code/llm/LLaVA-13b/code/porn_defense2.csv
        image_transforms:
        - target: torchvision.transforms.Resize
          params:
            size: 256
            interpolation: 3
        - target: torchvision.transforms.RandomCrop
          params:
            size: 256
        - target: torchvision.transforms.RandomHorizontalFlip
    target_finetune:
      target: ldm.data.simple.hf_dataset
      params:
        name: ../../code/llm/LLaVA-13b/code/llava_porn_finetune_I2T.csv
        image_transforms:
        - target: torchvision.transforms.Resize
          params:
            size: 256
            interpolation: 3
        - target: torchvision.transforms.RandomCrop
          params:
            size: 256
        - target: torchvision.transforms.RandomHorizontalFlip
    train_norm:
      target: ldm.data.simple.hf_dataset
      params:
        name: ../../datasets/coco-image-caption/train5w.csv
        image_transforms:
        - target: torchvision.transforms.Resize
          params:
            size: 256
            interpolation: 3
        - target: torchvision.transforms.RandomCrop
          params:
            size: 256
        - target: torchvision.transforms.RandomHorizontalFlip
    validation:
      target: ldm.data.simple.TextOnly
      params:
        captions:
        - "A pokemon with green eyes, large wings, and a hat"
        - "A cute bunny rabbit"
        - "Yoda"
        - "An epic landscape photo of a mountain"
        output_size: 256
        n_gpus: 2 # small hack to sure we see all our samples
    

lightning:
  find_unused_parameters: False

  modelcheckpoint:
    params:
      every_n_train_steps: 1
      save_top_k: -1
      monitor: null

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_all_val: True
        log_images_kwargs:
          use_ema_scope: False
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 4
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

  trainer:
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 10
    max_epochs: 5
    log_every_n_steps: 2
