input_blocks.1.1.transformer_blocks.0.attn1: 320
input_blocks.1.1.transformer_blocks.0.attn2: 320
input_blocks.2.1.transformer_blocks.0.attn1: 320
input_blocks.2.1.transformer_blocks.0.attn2: 320
input_blocks.4.1.transformer_blocks.0.attn1: 640
input_blocks.4.1.transformer_blocks.0.attn2: 640
input_blocks.5.1.transformer_blocks.0.attn1: 640
input_blocks.5.1.transformer_blocks.0.attn2: 640
input_blocks.7.1.transformer_blocks.0.attn1: 1280
input_blocks.7.1.transformer_blocks.0.attn2: 1280
input_blocks.8.1.transformer_blocks.0.attn1: 1280
input_blocks.8.1.transformer_blocks.0.attn2: 1280
middle_block.1.transformer_blocks.0.attn1: 1280
middle_block.1.transformer_blocks.0.attn2: 1280
output_blocks.10.1.transformer_blocks.0.attn1: 320
output_blocks.10.1.transformer_blocks.0.attn2: 320
output_blocks.11.1.transformer_blocks.0.attn1: 320
output_blocks.11.1.transformer_blocks.0.attn2: 320
output_blocks.3.1.transformer_blocks.0.attn1: 1280
output_blocks.3.1.transformer_blocks.0.attn2: 1280
output_blocks.4.1.transformer_blocks.0.attn1: 1280
output_blocks.4.1.transformer_blocks.0.attn2: 1280
output_blocks.5.1.transformer_blocks.0.attn1: 1280
output_blocks.5.1.transformer_blocks.0.attn2: 1280
output_blocks.6.1.transformer_blocks.0.attn1: 640
output_blocks.6.1.transformer_blocks.0.attn2: 640
output_blocks.7.1.transformer_blocks.0.attn1: 640
output_blocks.7.1.transformer_blocks.0.attn2: 640
output_blocks.8.1.transformer_blocks.0.attn1: 640
output_blocks.8.1.transformer_blocks.0.attn2: 640
output_blocks.9.1.transformer_blocks.0.attn1: 320
output_blocks.9.1.transformer_blocks.0.attn2: 320
